const one_text = document.querySelector('.one_text');
const two_text = document.querySelector('.two_text');
const three_text = document.querySelector('.three_text');
const four_text = document.querySelector('.four_text');
const five_text = document.querySelector('.five_text');
const six_text = document.querySelector('.six_text');
const seven_text = document.querySelector('.seven_text');
const eihgt_text = document.querySelector('.eihgt_text');
const nigth_text = document.querySelector('.nigth_text');
const diez_text = document.querySelector('.diez_text');
const once_text = document.querySelector('.once_text');
const doce_text = document.querySelector('.doce_text');
const trece_text = document.querySelector('.trece_text');
const catorce_text = document.querySelector('.catorce_text');
const quince_text = document.querySelector('.quince_text');
const dieciceis_text = document.querySelector('.dieciceis_text');

one_text.textContent = '<Button />';
two_text.textContent = '<Button variant=”outline” />';
three_text.textContent = '<Button variant=”text” />';
four_text.textContent = '<Button disableShadow />';
five_text.textContent = '<Button disabled />';
six_text.textContent = '<Button variant=”text” disabled />';
seven_text.textContent = '<Button startIcon=”local_grocery_store” />';
eihgt_text.textContent = '<Button endIcon=”local_grocery_store” />';
nigth_text.textContent = '<Button size=”sm” />';
diez_text.textContent = '<Button size=”md” />';
once_text.textContent = '<Button size=”lg” />';
doce_text.textContent = '<Button color=”default” />';
trece_text.textContent = '<Button color=”primary” />';
catorce_text.textContent = '<Button color=”secondary” />';
quince_text.textContent = '<Button color=”danger” />';
dieciceis_text.textContent = '&:hover, &:focus';